# Generated by Django 2.1.7 on 2019-03-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistanceType', models.CharField(choices=[('Emergency Ambulance', 'Emergency Ambulance'), ('Rescue and Evacuation', 'Rescue and Evacuation'), ('Fire-Fighting', 'Fire-Fighting'), ('Gas Leak Control', 'Gas Leak Control')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Handling', 'Handling'), ('Closed', 'Closed')], max_length=100)),
                ('level', models.CharField(choices=[('CAT1', 'CAT1'), ('CAT2', 'CAT2')], max_length=100)),
                ('descrition', models.TextField()),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('managedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSubcriber',
            fields=[
                ('phoneNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('Central Region', 'Central Region'), ('East Region', 'East Region'), ('North Region', 'North Region'), ('North-East Region', 'North-East Region'), ('West Region', 'West Region')], max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='assistance',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Incident'),
        ),
    ]
