# Generated by Django 2.1.7 on 2019-03-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='incident',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='reporter',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Incident'),
        ),
    ]
