# Generated by Django 2.1.7 on 2019-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='num_casualties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
