# Generated by Django 2.1.7 on 2019-03-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20190323_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.Report'),
        ),
    ]
